services:
  db:
    image: docker.io/library/postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
  adminer:
    image: docker.io/library/adminer
    restart: always
    ports:
      - 8080:8080

  # server:
  #   image: suivi-entretien
  #   build: .
  #   env_file:
  #     - .env.server
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   ports:
  #     - 3000:3000
